_target_: src.models.da_frcnn_detection_model.DaFrcnnDetectionModel

lr: 0.0025
weight_decay: 0.0001

da_net:
  _target_: src.models.modules.da_frcnn.DaFRCNN
  backbone_out_channels: 1024
  consit_weight: 0.1
  img_grl_weight: 0.025
  ins_grl_weight: 0.1