# https://wandb.ai

wandb:
  _target_: pytorch_lightning.loggers.wandb.WandbLogger
  project: "new-sada-classifier"
  name: ${name}
  save_dir: "."
  offline: False # set True to store all logs only locally
  id: null # pass correct id to resume experiment!
  entity: "eoghan" # set to name of your wandb team
  log_model: True
  prefix: ""
  job_type: "train"
  group: ""
  tags: []
